# Generated by Django 3.2.20 on 2023-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_post_tpk8l7', upload_to='images/'),
        ),
    ]
